### ISSUE TITLE
Changing a calendar's service_id causes stop_times to get deleted

### ISSUE THREAD

**Issue by evansiroky** [conveyal/gtfs-lib#203]
## Observed behavior

While editing this GTFS file ([gtfs_GL.zip](https://github.com/conveyal/gtfs-lib/files/2896582/gtfs_GL.zip)) in the datatools-ui editor, I changed the service_id on the calendar entry. Then, I checked some stop times in the timetable and noticed that they are completely missing for the even numbered trips. I have even verified that they are gone from the database.

## Expected behavior

Stop times should not be deleted when changing the service_id.

## Steps to reproduce the problem

See description.

## Notes on configuration and files required to reproduce the issue

gtfs-lib: https://github.com/conveyal/gtfs-lib/commit/5ec52854ac2c39dd94f8ac9d0f0fc051cf53d312
datatools-server: https://github.com/conveyal/datatools-server/commit/5943dfbe9e3acee0393c1e745a82f923a2483d2e
datatools-ui: https://github.com/conveyal/datatools-ui/commit/0f10fa25468e43b489942d4eb777706449dd6653

**Comment by landonreed** [comment]
That's disconcerting, @evansiroky. Any leads on what is going on there?

**Comment by evansiroky** [comment]
I haven't done anything more than verify that the issue is reproducible and check that there isn't anything funky in datatools-ui or datatools-server, so all I know is that it's probably something going on with gtfs-lib.

**Comment by landonreed** [comment]
Can you please update the description with the commit or branch you're using for gtfs-lib? I just tried with 5ec52854ac2c39dd94f8ac9d0f0fc051cf53d312 and the number of stop_times records stayed the same (53) after changing the service_id from 1 to 2.

**Comment by evansiroky** [comment]
Updated comment, using same gtfs-lib commit as you are, still seeing issue.

**Comment by evansiroky** [comment]
Issue reproduced in the above added test case and confirmed in CI build failure. See https://travis-ci.org/conveyal/gtfs-lib/jobs/500212360#L1345-L1350
