### ISSUE TITLE
Too many Postgres connections error on GraphQL query

### ISSUE THREAD

**Issue by landonreed** [conveyal/gtfs-lib#206]
## Observed behavior

The following error message was shown in the staging UI during any GraphQL fetch:

```
Error fetching GTFS entities via GraphQL

- Exception while fetching data (/feed) : org.postgresql.util.PSQLException: FATAL: remaining connection slots are reserved for non-replication superuser connections ({"line":3,"column":3})
```

This may be a configuration error for the staging server's postgres instance, but am logging it here because we may have something configured incorrectly in the connection pooling. cc @abyrd

**Update**: I just checked the # of connections with `select * from pg_stat_activity where datname = 'gtfs';` and found 97 rows.

## Expected behavior

GraphQL query should succeed.

## Steps to reproduce the problem

Go to an existing feed source and open the editor, or click the routes tab to trigger a GraphQL query.

## Any special notes on configuration used

N/A

## Version of datatools-server and datatools-ui if applicable (exact commit hash or branch name)

ui https://github.com/conveyal/datatools-ui/commit/544686bb3319a420371543461b98dd848229d833
server https://github.com/conveyal/datatools-server/commit/46d49ff7b647a817c211632eee5f048ed4f424d5

**Comment by abyrd** [comment]
Yes, sounds like the server is just configured to allow less connections than our pool. But it's worth checking into how we are creating so many connections. Most operations we're doing should not need to hold more than a couple connections open at once.

I guess the first thing to look at is the server configuration and pool connection, noting the max connections on each side.

**Comment by landonreed** [comment]
I'm not sure if this is the primary culprit, but it looks like we're not closing the db connection in the FeedFetcher (other instances that use a connection for GraphQL queries close the connection in a finally clause after the query):

https://github.com/conveyal/gtfs-lib/blob/2184e48de2d3549cf414a9b5d0870f682092236a/src/main/java/com/conveyal/gtfs/graphql/fetchers/FeedFetcher.java#L56-L58

**Comment by abyrd** [comment]
Yes, it's definitely important to release the connections back to the pool. And we need to make sure it's done even when exceptions occur. We'll have to search through the code for any such cases. There may be instrumentation we can add to flag idle connections that are never released.
