### ISSUE TITLE
LGPL vs. Apache

### ISSUE THREAD

**Issue by karussell** [conveyal/gtfs-lib#23]
Thanks for this library! The LICENSE files states the project stands under the Apache 2, but e.g. under src/main/java/com/conveyal/gtfs/model all classes seem to be LGPL. Is this particular model package under LGPL? Are there other exceptions?

BTW: why is trove4j there 2 times in the dependencies? https://github.com/conveyal/gtfs-lib/blob/master/pom.xml#L137
BTW2: do you plan to release to maven central?

**Comment by abyrd** [comment]
Hi @karussell, glad you're finding this useful. The license mismatch is a mistake. The model classes originally existed inside OpenTripPlanner (which is LGPL licensed) but were pulled out into this permissively-licensed repo. I wrote the original code in these model classes and as copyright holder planned to officially change the license from LGPL to MIT or Apache. I will update the license headers accordingly.

Trove appearing twice is also a mistake.

We do not have any plans to release to Maven Central. Conveyal has our own Maven repo, and automatic builds of all our libraries are available there.

In this case: http://maven.conveyal.com/com/conveyal/gtfs-lib/

**Comment by karussell** [comment]
Thanks for the insights!

> We do not have any plans to release to Maven Central

Any reason for this :) ? The problem then is that a usage of upstream projects will be more complex too or those projects are forced to release the gtfs-lib on their own. And once you've set up the release process to maven central all is very easy: http://central.sonatype.org/pages/ossrh-guide.html or http://central.sonatype.org/pages/requirements.html

**Comment by abyrd** [comment]
Can you explain what you mean by "usage of upstream projects will be more complex"? Why would they be forced to release their own gtfs-lib?

**Comment by karussell** [comment]
> Can you explain what you mean by "usage of upstream projects will be more complex"?
> Why would they be forced to release their own gtfs-lib?

We deploy our project to maven central and the complexity to use our project (in other projects) would increase (as you need to fiddle once more with the pom) and also our release process would be more complex and so we would just release the gtfs-lib to maven central under our subdomain to make things easier and more 'standard'.

Besides this, there is the recommendation that non-central deps should be avoided, see the [requirements](http://central.sonatype.org/pages/requirements.html): *These are the requirements for the pom file. In addition we discourage the usage of `<repositories>` and `<pluginRepositories>` and instead publish any required components to the Central Repository. This applies for your own components as well as for 3rd party artifacts.*

**Comment by abyrd** [comment]
I can understand that there's a guideline that it's better to have all dependencies in Central, and we may consider deploying some of our software there. But I still don't understand why it would be harder for other projects to use your project. My understanding is that Maven resolves transitive dependencies automatically, so a user of your library should only ever need to add a dependency entry for your library.

**Comment by karussell** [comment]
In the open source world probably you are right. But in restricted environments you often have a separate artifact repository which often only has access to maven central and other repos need special procedure do be added if possible at all.

**Comment by abyrd** [comment]
Thanks for the explanation. I can see the advantages to publishing to Maven Central for increasing code re-use. However, considering that Conveyal is almost entirely open source on principle, it's hard to justify additional effort and maintenance that will mainly assist companies operating in restricted (closed-source) environments: we are in some way subsidizing their business.

**Comment by karussell** [comment]
There seems to be something wrong with your repository. Please see the linked discussion.

**Comment by abyrd** [comment]
@karussell I just removed the extra dependency and removed the LGPL license headers from the model classes in the master branch. I have also taken steps toward publishing on Maven Central, which should become automatic soon. https://repo1.maven.org/maven2/com/conveyal/gtfs-lib/

Closing this ticket.

**Comment by karussell** [comment]
Thanks again for this!
