### ISSUE TITLE
slf4j binding warning

### ISSUE THREAD

**Issue by karussell** [conveyal/gtfs-lib#26]
As this project is a library the [logging dependencies](https://github.com/conveyal/gtfs-lib/blob/master/pom.xml#L128-L132) should be set to 'test' or 'runtime' scope to avoid binding the wrong slf4j binding and this warning: http://www.slf4j.org/codes.html#multiple_bindings

As a workaround one can use:
```xml
        <dependency>
            <groupId>com.conveyal</groupId>
            <artifactId>gtfs-lib</artifactId>
            <version>1.2.0</version>

            <exclusions>
                <exclusion> 
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-simple</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by landonreed** [comment]
Thanks @karussell!  We're glad you like it.

**Comment by karussell** [comment]
Sorry, probably a small misunderstanding. When we integrate the lib in our projects we get this slf4j warning and the workaround was for those using applications.

To fix this in gtfs-lib itself you need to add `<scope>test</scope>` (or runtime) [here](https://github.com/conveyal/gtfs-lib/blob/master/pom.xml#L131)
