### ISSUE TITLE
Some route_type values are not support 

### ISSUE THREAD

**Issue by MathStPierre** [conveyal/gtfs-lib#267]
Some GTFS data are using route_type data beyond the 0-7 ID range even though some of those route_type are described in the documentation below : 

https://developers.google.com/transit/gtfs/reference/extended-route-types

## Expected behavior

Extended route types should be supported, possibly remap to some 0-7 ID.

## Steps to reproduce the problem

Use any GTFS dataset and change the route_type ID to something beyond the 0-7 ID range.

## Notes on configuration and files required to reproduce the issue

The issue was found in the GraphHopper library.

**Comment by binh-dam-ibigroup** [comment]
Closed with #343 for route type validation and https://github.com/ibi-group/datatools-server/pull/453 that contains extended GTFS route types.
