### ISSUE TITLE
Build broken at HEAD?

### ISSUE THREAD

**Issue by blackmad** [conveyal/gtfs-lib#268]
## Observed behavior

Tried to build from head in git and got test errors when doing so. This is at commit 1d1ae246991014f14fef451623e343f0f7a3cb94 (HEAD -> dev, origin/master, origin/dev, origin/HEAD)

(base) ➜  gtfs-lib git:(dev) mvn package
.....
3550 [main] INFO com.conveyal.gtfs.GTFSFeed - 2 errors
3550 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: agency line 1, field 'agency_url': No value supplied for a required column.
3550 [main] INFO com.conveyal.gtfs.GTFSFeed - GTFSError: transfers line 0: Table is present in zip file, but it has no entries.
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.937 sec
Running com.conveyal.gtfs.GeometriesTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.05 sec

Results :

Failed tests:   canLoadFeedWithBadDates(com.conveyal.gtfs.GTFSTest): Integration test passes(..)
  canLoadAndExportSimpleAgency(com.conveyal.gtfs.GTFSTest): (..)
  canLoadAndExportSimpleAgencyInSubDirectory(com.conveyal.gtfs.GTFSTest): (..)
  canLoadFeedWithErrors(com.conveyal.gtfs.GTFSTest): Integration test passes(..)
  canLoadAndExportSimpleAgencyWithOnlyCalendarDates(com.conveyal.gtfs.GTFSTest): (..)

Tests in error: 
  com.conveyal.gtfs.loader.JDBCTableWriterTest: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
  com.conveyal.gtfs.graphql.GTFSGraphQLTest: org.postgresql.util.PSQLException: Connection to localhost:5432 refused. Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.

Tests run: 23, Failures: 5, Errors: 2, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  7.915 s
[INFO] Finished at: 2020-01-10T15:40:48-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project gtfs-lib: There are test failures.
[ERROR] 
[ERROR] Please refer to /private/tmp/gtfs-lib/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException

## Expected behavior

all tests pass / can build a jar

**Comment by abyrd** [comment]
Hi, at least one of the problems is that you need a Postgres server running on localhost:5432.

**Comment by evansiroky** [comment]
As @abyrd mentions, an actively running local instance of Postgres is required in order for the tests to pass. Please re-open if you still encounter errors running the tests once they can be run with a running local instance of Postgres.
