### ISSUE TITLE
Editor: Delete route does not delete related pattern stops (and possibly patterns)

### ISSUE THREAD

**Issue by landonreed** [conveyal/gtfs-lib#271]
## Observed behavior

In Data Tools, create route, add pattern (with pattern stops). Next, delete route. Then, try to delete a stop that was used in a pattern stop on the deleted route. Delete stop operation fails.

![image](https://user-images.githubusercontent.com/2370911/73695032-476c8b00-46a7-11ea-9b16-17bf8e38d5a5.png)

## Expected behavior

Deleting the route should delete the patterns that reference the route as well as the pattern stops. It appears that pattern stops (and maybe patterns) are not being deleted properly.

## Steps to reproduce the problem

See above.

## Notes on configuration and files required to reproduce the issue

N/A

**Comment by binh-dam-ibigroup** [comment]
Fixed by #350.
