### ISSUE TITLE
stop_times.continuous_drop_off/continous_pickup incorrectly loaded?

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [conveyal/gtfs-lib#325]
## Observed behavior

A bug here https://github.com/conveyal/gtfs-lib/blob/dev/src/main/java/com/conveyal/gtfs/model/StopTime.java#L93 may prevent the `continuous_pickup`/`continuous_drop_off` fields in the `stop_times` GTFS tables from being imported correctly.

## Expected behavior

The mentioned fields in `stop_times` should be loaded properly.

## Steps to reproduce the problem

Load a GTFS feed with non-default values in the fields mentioned.
Observe that the values in the GTFS editor don't correspond to the values in the GTFS file.

## Notes on configuration and files required to reproduce the issue

datatools-server: any version that contains https://github.com/ibi-group/datatools-server/pull/387
datatools-UI: any version that contains https://github.com/ibi-group/datatools-ui/pull/668

**Comment by miles-grant-ibigroup** [comment]
I don't think this is an issue with this library. Running `java -cp target/gtfs-lib-6.2.3-SNAPSHOT-shaded.jar com.conveyal.gtfs.GTFS --load gtfs.zip --validate --json ./results` writes to the database correctly.

**Comment by miles-grant-ibigroup** [comment]
I am also unable to reproduce in datatools. Everything is working there as well.

**Comment by miles-grant-ibigroup** [comment]
Still working correctly, although I'm seeing some errors during the package build.

**Comment by binh-dam-ibigroup** [comment]
Should have mentioned the culprit line of code: https://github.com/conveyal/gtfs-lib/blob/dev/src/main/java/com/conveyal/gtfs/model/StopTime.java#L93.

**Comment by miles-grant-ibigroup** [comment]
Both `continuous_drop_off` and `continuous_pickup` are being correctly imported.
