### ISSUE TITLE
Exported location group used in a schedule is flagged as unused.

### ISSUE THREAD

**Issue by binh-dam-ibigroup** [conveyal/gtfs-lib#359]
## Observed behavior

Upon loading a feed zip with a location group used in a schedule, the validation results show that the location group is unused.

## Expected behavior

The location group should not be flagged as unused.

## Steps to reproduce the problem

1. In the GTFS editor, create a location group, add it to a pattern of a route, and populate the schedule for that location group.
2. Export and download a snapshot of the GTFS editor
3. Create a new feed source and import the exported snapshot
4. Observe the validation warning regarding the unused location group. 

## Notes on configuration and files required to reproduce the issue

Affected branch: `dev-flex`.

**Comment by br648** [comment]
@binh-dam-ibigroup can I confirm that datatools-server and datatools-ui are both on branch `dev-flex`? I'm getting errors working off of these branches when attempting to edit a route:

`New Route's route_id value (7sjh) conflicts with an existing record in table.`

If I change the route id, I get this instead:

`Validation error of type FieldUndefined: Field 'pattern_location_groups' in type 'pattern' is undefined @ 'feed/routes/patterns/pattern_location_groups'`

cc @miles-grant-ibigroup

**Comment by miles-grant-ibigroup** [comment]
Are you creating/importing a new feed from scratch? We've had some issues adjusting older feeds as the database structure changes.

**Comment by br648** [comment]
@miles-grant-ibigroup I'm attempting to create from scratch. New project and new feed source.

**Comment by miles-grant-ibigroup** [comment]
I just tried with a clean database and fresh branches and was unable to replicate. Did you run `mvn clean`? I've found that sometimes the wrong gtfs-lib version is loaded

**Comment by br648** [comment]
yeah nevermind, did a clean and compile to resolve. Sorry about that!

**Comment by br648** [comment]
@binh-dam-ibigroup Did you add a location to the location group? The download fails if I don't do this, which is something I'll need to address separately (NPE if there are no Location Groups). If I add the location and import the snapshot, I don't get the validation error.

**Comment by br648** [comment]
@binh-dam-ibigroup validation errors I'm getting:
![image](https://user-images.githubusercontent.com/28602741/189885945-92c513be-b85c-4104-bfd4-1e7640084978.png)

**Comment by binh-dam-ibigroup** [comment]
Unable to reproduce after latest code update.
