### ISSUE TITLE
Clarification regarding dependencies

### ISSUE THREAD

**Issue by karussell** [conveyal/gtfs-lib#44]
Do we need `aws-java-sdk-s3` and why is `gt-epsg-hsql` using a different version then the rest?

And which **source code** changes were requires to jackson that you need a modified jackson2-geojson? BTW: We use [this repo](https://github.com/bedatadriven/jackson-datatype-jts) which is also in maven central.

**Comment by mattwigway** [comment]
AWS Java SDK S3 is required for the GTFSCache code. I think that the geotools versions should all be the same, that sounds like a bug.

We didn't make any source code changes, we just needed it to be available in a maven repository, which it wasn't at the time. We could probably switch but it's going to be a bit of effort to ensure everything is being serialized properly.

**Comment by karussell** [comment]
So when I have a private GTFS feed it could be stored/cached in AWS? What is the purpose of the aws cache exactly?

**Comment by mattwigway** [comment]
Conveyal's main use of GTFS-lib is as a library in other applications, most of which require GTFS storage on S3. Thus GTFS-lib provides the [GTFSCache](https://github.com/conveyal/gtfs-lib/blob/master/src/main/java/com/conveyal/gtfs/GTFSCache.java) class. If your application does not use this cache, data will not be stored on S3.

**Comment by karussell** [comment]
Ah, makes sense. Thanks for the clarification!
